export const fakeData = [
  {
    id: 1,
    column1: "Master Plan 14 Days",
    column2: "$75000",
    column3: "$1875",
    column4: "$76875",
    column5: "12/08/2023",
    column6: "28/08/2023",
  },
  // {
  //   id: 2,
  //   column1: "Master Plan 14 Days",
  //   column2: "$75000",
  //   column3: "$1875",
  //   column4: "$76875",
  //   column5: "12/08/2023",
  //   column6: "28/08/2023",
  // },
  // {
  //   id: 3,
  //   column1: "Data",
  //   column2: "Data",
  //   column3: "Data",
  //   column4: "Data",
  //   column5: "Data",
  //   column6: "Data",
  // },
  // {
  //   id: 4,
  //   column1: "Data",
  //   column2: "Data",
  //   column3: "Data",
  //   column4: "Data",
  //   column5: "Data",
  //   column6: "Data",
  // },
  // {
  //   id: 5,
  //   column1: "Data",
  //   column2: "Data",
  //   column3: "Data",
  //   column4: "Data",
  //   column5: "Data",
  //   column6: "Data",
  // },
  // {
  //   id: 6,
  //   column1: "Data",
  //   column2: "Data",
  //   column3: "Data",
  //   column4: "Data",
  //   column5: "Data",
  //   column6: "Data",
  // },
  // {
  //   id: 7,
  //   column1: "Data",
  //   column2: "Data",
  //   column3: "Data",
  //   column4: "Data",
  //   column5: "Data",
  //   column6: "Data",
  // },
  // {
  //   id: 8,
  //   column1: "Data",
  //   column2: "Data",
  //   column3: "Data",
  //   column4: "Data",
  //   column5: "Data",
  //   column6: "Data",
  // },
  // {
  //   id: 9,
  //   column1: "Data",
  //   column2: "Data",
  //   column3: "Data",
  //   column4: "Data",
  //   column5: "Data",
  //   column6: "Data",
  // },
  // {
  //   id: 10,
  //   column1: "Data",
  //   column2: "Data",
  //   column3: "Data",
  //   column4: "Data",
  //   column5: "Data",
  //   column6: "Data",
  // },
];

export default fakeData;